### ISSUE TITLE
Only keywords in default locale are attented to by tsvConverter

### ISSUE THREAD

**Issue by martinpub** [ajnyga/tsvConverter#11]
Hi! Other keywords that those in the default locale seem to be disregarded by tsvConverter.

A somewhat minimal example is attached: [ajnyga-example-kw.xlsx](https://github.com/ajnyga/tsvConverter/files/2643712/ajnyga-example-kw.xlsx)

**Comment by ajnyga** [comment]
fixed in https://github.com/ajnyga/tsvConverter/releases/tag/1.1.0.13

**Comment by martinpub** [comment]
Great, thanks!
