### ISSUE TITLE
What about if the artile  have other main language

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#3]
I have a journal in Spanish. 

Is it a good idea, just to upload all the fields in Spanish, and the translations fields, like fi:abstract, change to en:abstract and upload an abstract in English?.

**Comment by ajnyga** [comment]
Hi,

If you have all articles and all metadata in Spanish and an additional English abstract, then I would:
1. Set https://github.com/ajnyga/tsvConverter/blob/master/convert.php#L12 to Spanish
2. Add an extra en:abstract field to the excel sheet. 

So basically exactly like you thought. 

I would test this first for example with one issue and upload the XML file to a OJS test installation. This way you can check that the data is imported as expected and make possible corrections to the excel sheet if needed.

**Comment by josuevalrob** [comment]
Yeah, its work perfectly fine. 
I can navigate with the journal in Spanish and everything is fine. 

When I change to English, the abstract change too. 

How can I add a **title** in English? Or in another language? 

Can I contribute to your code?

**Comment by ajnyga** [comment]
You should be able to add en:title field to the excel sheet.

And of course you can.
