### ISSUE TITLE
 Allowed memory size

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#4]
I am trying to create a file with 124 imports. But i get this error: 

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate
 36 bytes) in C:\Users\Administrador\Downloads\tsvConverter-master\phpexcel\Clas
ses\PHPExcel\Worksheet.php on line 2501

Can I increase the Php memory size??

**Comment by ajnyga** [comment]
hmm, after googling seems that the phpExcel library is not particularly good with using memory. See for example https://stackoverflow.com/questions/4817651/phpexcel-runs-out-of-256-512-and-also-1024mb-of-ram

I have imported much larger tables though, so I am not sure why 124 lines would be a problem.
You could try to add your memory limit by editing php.ini or you could divide your excel to two separate sheets. Just do not cut the sheet in the middle of an issue.

**Comment by ajnyga** [comment]
I can not get the script crash this way. I dropped the memory limit down to 32M and tried to convert the larger xls file you sent me, the one with 77 rows. So I can not figure out why 124 rows would exhaust over 500 megabytes of memory?

**Comment by josuevalrob** [comment]
maybe is a problem with my server?¿

**Comment by josuevalrob** [comment]
was a problem with the memory limit.
