### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#5]
Sorry for ask this, but i dont get how to handle this error:

11:43:47 Validating data
11:43:47 ERROR: Issue year missing
11:43:47 ERROR: Issue publication date missing
11:43:47 ERROR: article title missing for the given default locale
11:43:47 ERROR: section title missing for the given default locale
11:43:47 ERROR: section abbreviation missing for the given default locale

This is my table in excel:
[Libro1.xlsx](https://github.com/ajnyga/tsvConverter/files/1723396/Libro1.xlsx)

**Comment by ajnyga** [comment]
did you resolve this?

**Comment by josuevalrob** [comment]
Yeah, was some problem with the data in excel. 
Even if I had an empty line, I had to delete it, (not just delete the content), to let it clean.

**Comment by ajnyga** [comment]
ok, thanks. I probably could add a reference to the row that creates the error to make it easier to debug.

**Comment by josuevalrob** [comment]
that could be perfect, because in some cases, I have a lot of lines, and in one I forget to put the author name.... and know where is that, takes a lot of time
