### ISSUE TITLE
Memory allocation failed : growing buffer

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#6]
I have an excel file with 4 lines.  
[180.xlsx](https://github.com/ajnyga/tsvConverter/files/1731158/180.xlsx)

After convert it to XML and try to import it it got this: 

> Validation errors:
> Memory allocation failed : growing buffer
> Memory allocation failed : growing buffer
> The document has no document element.

If i just remove one line, and convert the file, i got this: 

> The import completed successfully. The following items were imported:
> Vol 180 (2015): Ingeniería Civil

I dont know what is the problem, if it is with the ojs (i have try it in multiple sites) or the convert.php. 

Now imagine if i want to upload 1200 lines... 

Thanks for your help!

**Comment by ajnyga** [comment]
I guess there is an error in the XML, not sure what it is. I will do some work on this probably tomorrow so I can take a look.

The largest import I have made had over 600 articles, so that should not be a problem.

**Comment by josuevalrob** [comment]
The xml is really weird... 
I can send you both via email.

**Comment by ajnyga** [comment]
Sure ajnyga@gmail.com
It could be that the style changes (grey background etc.) you have made to the excel sheet is affecting the result in some way.

**Comment by josuevalrob** [comment]
Okey i clean it. But the still the problem.

**Comment by ajnyga** [comment]
As I mentioned in the other threat I was able to convert both the smaller and the larger xls file you sent me by email. I did fix a couple of small things in the script but those did not affect the actual result.

I have a feeling that the memory error in the actual XML import in the OJS end has something to do with the very large memory limit you mentioned on the forum. You should use a value like 256M or 512M or even less depending on your server. I think you had something like 256000M. I was able to import the XML files generated from the larger xls file with 128M.

**Comment by josuevalrob** [comment]
Okey, i will check my xampp configurations

**Comment by josuevalrob** [comment]
Was a problem with the memory_limit in php.
