### ISSUE TITLE
Two questions. 

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#7]
1) How can I send Keywords? They are separated by commas. 
2)  Can I separate the exported XML files, not in different years, but in different sheets from excel? Or, In a different Issue Number.?

**Comment by ajnyga** [comment]
Hi,

Sorry I have totally missed your questions.

1. The latest version should support a keywords field. The words have to be semicolon separated. Of course you can easily change the character used in the explode function and use comma instead.

2. You can of course separate it in different sheets, but the code will still try to create files per year. The reason I did that was to limit the size of the exported file. You can of course remove the code that splits it to years and instead do the splitting in the excel sheets.

**Comment by josuevalrob** [comment]
Perfect! thanks
