### ISSUE TITLE
Warnings/notices and no XML produced

### ISSUE THREAD

**Issue by martinpub** [ajnyga/tsvConverter#8]
Hi @ajnyga,

Thank you for this contribution! I'm testing the plugin with the attached test spreadsheet: 
[test_record.xlsx](https://github.com/ajnyga/tsvConverter/files/2576380/test_record.xlsx)

It passes validation, but no XML file is produced as a result. Here is the log, including some warnings/notices:

> 14:14:56 Creating a new PHPExcel object
> 14:14:56 Creating an array
> 14:14:56 Validating data
> 14:14:56 Preparing data for output
> 14:14:56 Starting XML output
> 14:14:56 Closing XML file
> PHP Notice:  Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 379
> 
> Notice: Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 379
> PHP Warning:  fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 379
> 
> Warning: fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 379
> PHP Notice:  Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 380
> 
> Notice: Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 380
> PHP Warning:  fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 380
> 
> Warning: fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 380
> PHP Notice:  Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 381
> 
> Notice: Undefined variable: xmlfile in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 381
> PHP Warning:  fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 381
> 
> Warning: fwrite() expects parameter 1 to be resource, null given in /usr/local/ojsgit/plugins/importexport/tsvConverter/convert.php on line 381
> 14:14:56 Conversion finished

Any ideas? Your example.xlsx works fine.

Thanks!

**Comment by ajnyga** [comment]
Can you try what happens if you add another row to the file?

**Comment by martinpub** [comment]
Still the same result, I'm afraid.

**Comment by ajnyga** [comment]
I updated convert.php in the master branch. Can you check if it works with that version (there was a small bug there that was visible with less than three rows) Should work now I think...

**Comment by martinpub** [comment]
@ajnyga Yes, thank you very much, it works now!

**Comment by ajnyga** [comment]
Great! I will update the release. Thanks for the feedback!

**Comment by martinpub** [comment]
Perfect! I might get back, we are working on a backlist import project and are planning to use tsvConverter to generate the OJS XML import files, as it simplifies the procedure.

**Comment by martinpub** [comment]
@ajnyga Good to know! We have MODS XML data from [DiVA](http://www.diva-portal.org), and are planning to use [Catmandu](http://librecat.org/) for the transformation to tsvConverter's spreadsheet. Any input is appreciated, I'm working on the mapping right now.

**Comment by ajnyga** [comment]
The script I made is very very simple php script. The tagged format output is plain text and the content seems to vary from journal to journal. So I usually tweak the script to get the best output possible. In general the metadata production is something that the journals do, we just provide the service of converting it to XML and importing it to OJS, and of course help with the questions concerning the excel sheet. We do not have the resources to actually start filling the sheet on behalf of the journals.

This is the tagged format output:
```
RT Journal Article
A1 Ainiala, Terhi,
T1 Paikannimien kerrostumat maaseudulla ja kaupungissa nimistöntutkijan kohteina
SN 1456-3010
YR 2018
JF Elore
VO 25 
IS 
LA fin
NO Ajatteleva maisema
K1 paikannimet
K1 nimistöntutkimus
UL https://arto.linneanet.fi/vwebv/holdingsInfo?bibId=2494869
UL https://journal.fi/elore/article/view/72817

RT Journal Article
A1 Anttonen, Salli,
T1 Lectio praecursoria at the University of Eastern Finland 25 November 2017
SN 1456-3010
YR 2018
JF Elore
VO 25 
IS 
LA fin
NO Ajatteleva maisema
UL https://arto.linneanet.fi/vwebv/holdingsInfo?bibId=2502521
UL https://journal.fi/elore/article/view/72822

RT Journal Article
A1 Anttonen, Salli,
T1 The quest for authenticity in popular music cultures : lectio praecursoria at the University of Eastern Finland 25 November 2017
SN 1456-3010
YR 2018
JF Elore
VO 25 
IS 
LA eng
K1 populaarimusiikki
K1 diskurssi
K1 autenttisuus
UL https://arto.linneanet.fi/vwebv/holdingsInfo?bibId=2494872
UL https://journal.fi/elore/article/view/72822
```

**Comment by martinpub** [comment]
Thanks @ajnyga! We will go with our MODS XML --> tsvConverter converter though.

Any chance of supporting remote galleys in a future release BTW?

**Comment by ajnyga** [comment]
What does the XML output from OJS look like for remote galleys?

**Comment by martinpub** [comment]
It's very simple, here is an example:

```
  <article_galley xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" approved="false" xsi:schemaLocation="http://pkp.sfu.ca native.xsd">
    <id type="internal" advice="ignore">15902</id>
    <name locale="en_US">PDF (DiVA)</name>
    <seq>2</seq>
    <remote src="http://urn.kb.se/resolve?urn=urn:nbn:se:miun:diva-xyz"/>
  </article_galley>
```

**Comment by ajnyga** [comment]
The logic could be that if the file column has a value that starts with http or https, it would be regarded as an external galley. What do you think?

Of course you could even fetch the file contents and save it as a regular galley, but that is not what you want?

**Comment by martinpub** [comment]
That sounds like a good idea! And no need for a new column (even though the semantics is slightly off when it's a URL and not a file, but that's a minor point).

No, we would like galley links to backlist articles already published in DiVA, to keep backlist statistics there etc., while having full backlist metadata in OJS.

**Comment by ajnyga** [comment]
Then I think it is better to introduce a new column for the remote url and preserve the current file column for the functionality that would fetch the galley contents from an url. 

This should be an easy addition, I will look at it later today.

**Comment by martinpub** [comment]
Much appreciated! And introducing a new column is a better idea, I agree.

**Comment by ajnyga** [comment]
Hi,

Added support for remote galleys, but did not introduce a new field after all. 
So you can just use the current file# field and add an url there starting with http or https. The converter will then check if the file name given there is an url and if it is, it will treat it as a remote galley.

Did not have much time test this, so let me know if it does not work.

**Comment by martinpub** [comment]
Awesome, thank you very much! Will test asap.
