### ISSUE TITLE
Remote galleys fail validation

### ISSUE THREAD

**Issue by martinpub** [ajnyga/tsvConverter#9]
Hi,

When supplying galley URL:s in the file columns, tsvConverter gives the following error message for each galley:

`16:50:50 ERROR: file missing /usr/local/ojsgit/plugins/importexport/tsvConverter/files/[pdf URL]`

It seems that the file validation is treating the URLs as filenames, looking in the files/ subdir of the plugin root?

**Comment by ajnyga** [comment]
fixed in https://github.com/ajnyga/tsvConverter/releases/tag/1.1.0.13

**Comment by martinpub** [comment]
Excellent, thanks!
